[package]
build = "build.rs"
edition = "2021"
name = "ethics-pipeline"
version = "0.1.0"

[dependencies]
anyhow = "1.0.100"
bytes = "1.11.0"
clap = { version = "4.5.53", features = ["derive"] }
flate2 = "1.1.5"
glob = "0.3.3"
hf-hub = "0.4.3"
prost = "0.14.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokenizers = "0.22.1"
tokio = { version = "1.48.0", features = ["fs", "io-util", "macros", "rt-multi-thread"] }
toml = "0.9.8"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
zstd = "0.13.3"

[build-dependencies]
prost-build = "0.14.1"
